blogg/urls.py
from django.urls import path

from blogg.apps import BloggConfig
from blogg.views import BlogPostListView, BlogPostCreateView, BlogPostUpdateView, BlogPostDetailView, BlogPostDeleteView

app_name = BloggConfig.name


urlpatterns = [
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('', BlogPostListView.as_view(), name='list'),
    path('edit/<int:pk>/', BlogPostUpdateView.as_view(), name='edit'),
    path('view/<int:pk>/', BlogPostDetailView.as_view(), name='view'),
    path('delete/<int:pk>/', BlogPostDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('blogg/', include('blogg.urls', namespace='blogg')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import ProductListView, ContactsView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, VersionCreateView, VersionDeleteView, VersionListView, VersionUpdateView, VersionDetailView

app_name = MainConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('products/<int:pk>', ProductDetailView.as_view(), name='products'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('create_version/<int:pk>/', VersionCreateView.as_view(), name='create_version'),
    path('update_version/<int:pk>/', VersionUpdateView.as_view(), name='update_version'),
    path('version_detail/<int:pk>/', VersionDetailView.as_view(), name='version_detail'),
    path('delete_version/<int:pk>/', VersionDeleteView.as_view(), name='delete_version'),
    path('versions/<int:pk>/', VersionListView.as_view(), name='list_versions'),
]

blogg/models.py
from django.db import models

# Create your models here.
NULLABLE = {'null': True,
            'blank': True}
class BlogPost(models.Model):
    title = models.CharField(max_length=200, verbose_name='заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='posts/', verbose_name='изображение', **NULLABLE)
    date_of_creation = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=False, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'

blogg/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from pytils.translit import slugify
from django.core.mail import send_mail

# Create your views here.
from blogg.models import BlogPost
from config.settings import EMAIL_HOST_USER


class BlogPostListView(ListView):
    model = BlogPost

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset

class BlogPostCreateView(CreateView):
    model = BlogPost
    fields = ('title', 'content', 'is_published', 'preview',)
    success_url = reverse_lazy('blogg:list')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()

        return super().form_valid(form)

class BlogPostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = BlogPost
    permission_required = 'blogg.change_blogpost'
    fields = ('title', 'content', 'is_published', 'preview',)

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blogg:view', args=[self.kwargs.get('pk')])


class BlogPostDetailView(DetailView):
    model = BlogPost

    @staticmethod
    def send_notification(title, views_count):
        send_mail(
            subject='Blog',
            message=f'Ваша статья {title} достигла {views_count} просмотров!',
            from_email=EMAIL_HOST_USER,
            recipient_list=["metmaria23@gmail.com"]
        )

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        if self.object.views_count >= 2:
            self.send_notification(self.object.title, self.object.views_count)

        return self.object


class BlogPostDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('blogg:list')

blogg/templates/blogg/blogpost_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить пост "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'blogg:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blogg/templates/blogg/blogpost_detail.html
{% extends 'main/base.html' %}
{% load blog_media_tag %}
{% block content %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.title }} ({{ object.slug }})</h4>
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title">{{ object.content }}</h1>
            <img class="card-img-top" src="{{ object.preview|blog_media_tag}}">
            <p> Просмотры: {{ object.views_count }}</p>
        </div>
    </div>
</div>
{% endblock %}

blogg/templates/blogg/blogpost_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Обновить
                            {% else %}
                            Создать
                        {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blogg/templates/blogg/blogpost_list.html
{% extends 'main/base.html' %}
{% load blog_media_tag %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blogg:create' %}">Добавить пост</a>
</div>
<div class="row">
    {% for object in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <p class="card-text">
                    {% if object.is_published %}
                    {{ object|title }}
                    {% else %}
                    <span class="text-muted">{{ object|title }}</span>
                    {% endif %}
                </p></div>
            <div class="card-body">
                <h2 class="card-title pricing-card-title">{{ object.content|slice:5 }} ... </h2>
                <img class="card-img-top" src="{{ object.preview|blog_media_tag}}">
                <h4 class="card-title pricing-card-title">{{ object.date_of_creation }}</h4>
            </div>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'blogg:view' object.pk %}"
                       class="btn btn-sm btn-outline-secondary">View full post</a>

                    <a href="{% url 'blogg:edit' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Edit post</a>
                    {% if perms.blogg.change_blogpost %}
                    <a href="{% url 'blogg:delete' object.pk %}"
                       class="btn btn-sm btn-outline-danger">Delete post</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}