blogg/urls.py
from django.urls import path

from blogg.apps import BloggConfig
from blogg.views import BlogPostListView, BlogPostCreateView, BlogPostUpdateView, BlogPostDetailView, BlogPostDeleteView

app_name = BloggConfig.name


urlpatterns = [
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('', BlogPostListView.as_view(), name='list'),
    path('edit/<int:pk>/', BlogPostUpdateView.as_view(), name='edit'),
    path('view/<int:pk>/', BlogPostDetailView.as_view(), name='view'),
    path('delete/<int:pk>/', BlogPostDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('blogg/', include('blogg.urls', namespace='blogg')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import ProductListView, ContactsView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, VersionCreateView, VersionDeleteView, VersionListView, VersionUpdateView, VersionDetailView

app_name = MainConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('products/<int:pk>', ProductDetailView.as_view(), name='products'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('create_version/<int:pk>/', VersionCreateView.as_view(), name='create_version'),
    path('update_version/<int:pk>/', VersionUpdateView.as_view(), name='update_version'),
    path('version_detail/<int:pk>/', VersionDetailView.as_view(), name='version_detail'),
    path('delete_version/<int:pk>/', VersionDeleteView.as_view(), name='delete_version'),
    path('versions/<int:pk>/', VersionListView.as_view(), name='list_versions'),
]

main/models.py
from django.db import models

from users.models import User

# Create your models here.

NULLABLE = {'null': True,
            'blank': True}

class Category(models.Model):
    category_name = models.CharField(max_length=100, verbose_name='наименование')
    category_description = models.CharField(max_length=200, verbose_name='описание')

    def __str__(self):
        return f'{self.category_name} {self.category_description}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('category_name',)
        permissions = [
            ('can_edit_category_name', 'Can edit category name'),
        ]


class Product(models.Model):
    product_name = models.CharField(max_length=100, verbose_name='наименование')
    product_description = models.CharField(max_length=200, verbose_name='описание')
    product_image = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    product_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    product_price = models.IntegerField(verbose_name='цена за покупку')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец', **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name='опубликовано')

    def __str__(self):
        return f'{self.product_name} {self.product_description}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('product_name',)
        permissions = [
            ('can_edit_product_description', 'Can edit product description'),
            ('can_edit_is_published', 'Can edit product publication'),
        ]



class Version(models.Model):
    # product = models.CharField(max_length=100, verbose_name='продукт')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='version',
                                verbose_name='наименование')
    version_no = models.IntegerField(verbose_name='номер версии')
    version_name = models.CharField(max_length=100, verbose_name='название версии')
    active_version = models.BooleanField(default=True, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.product} {self.version_name}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

main/forms.py
from django import forms

from main.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'active_version':
                field.widget.attrs['class'] = ' form-check-input'

class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        # fields = '__all__'
        fields = ('product_name', 'product_description', 'product_image', 'product_price', 'product_category',)
        # exclude = ('is_active')

    def clean_product_name(self):
        cleaned_data = self.cleaned_data['product_name']
        banned_words = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево',
                        'бесплатно', 'обман', 'полиция', 'радар')

        for word in banned_words:
            if word in cleaned_data:
                raise forms.ValidationError(f'В названии продукта присутствует запрещенное слово {word}!')

        return cleaned_data

    def clean_product_description(self):
        cleaned_data = self.cleaned_data['product_description']
        banned_words = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево',
                        'бесплатно', 'обман', 'полиция', 'радар')

        for word in banned_words:
            if word in cleaned_data:
                raise forms.ValidationError(f'В описании продукта присутствует запрещенное слово {word}!')

        return cleaned_data

class ProductModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('product_description', 'is_published', 'product_category')

class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        exclude = ('product',)
        # fields = '__all__'

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from config import settings
from main.forms import ProductForm, VersionForm, ProductModeratorForm
from main.models import Product, Version


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'product_list.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     products = context['object_list']
    #     for product in products:
    #         active_version = product.version.filter(active_version=True).first()
    #         product.active_version = active_version
    #     return context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if settings.CACHE_ENABLED:
            key = f'product_list'
            products = cache.get(key)
            if products is None:
                products_list = context['object_list']
                for product in products_list:
                    active_version = product.version.filter(active_version=True).first()
                    product.active_version = active_version

                cache.set(key, products_list)
            else:
                context['products'] = products
            return context

class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    success_url = reverse_lazy('main:index')


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('main:index')

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.product_name)
            new_post.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('main:index')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.product_name)
            new_post.save()

        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm('main.can_edit_product_description') and user.has_perm('main.can_edit_is_published'):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('main:index')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        raise PermissionDenied


class ContactsView(TemplateView):
    template_name = 'main/contacts.html'

    def post(self, request):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f"Человечек {name} "
              f"ввел свой номер телефона {phone} "
              f"с таким сообщением {message}")
        context = self.get_context_data()
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Contacts'
        return context


class VersionListView(ListView):
    model = Version

    def get_queryset(self, *args, **kwargs):
        return Version.objects.filter(product=Product.objects.get(pk=self.kwargs.get('pk')))


class VersionCreateView(CreateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('main:index')

    def form_valid(self, form):
        if form.is_valid():
            product_pk = self.kwargs.get("pk")
            product = get_object_or_404(Product, pk=product_pk)
            form.instance.product = product
        return super().form_valid(form)

class VersionUpdateView(UpdateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('main:index')

class VersionDetailView(DetailView):
    model = Version
    # context_object_name = 'versions'

class VersionDeleteView(DeleteView):
    model = Version
    success_url = reverse_lazy('main:index')

main/templates/main/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div>
    {% include 'main/includes/inc_main_menu.html' %}
</div>


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    <div class="row text-center">
        {% block content %}
        {% endblock %}
    </div>
</div>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/contacts.html
{% extends 'main/base.html' %}
{% block content %}

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message" placeholder="Контактный телефон"
                                      required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load media_tag %}
{% block content %}
<div class="row">
    {% for object in products_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.product_name }}</h4>
            </div>
            <div class="card-body">
                <h2 class="card-title pricing-card-title">{{ object.product_description|slice:5 }} ... </h2>
                <h1 class="card-title pricing-card-title">{{ object.product_price }} RUB</h1>
                <a href="{% url 'main:products' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Подробнее
                    о товаре</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/product_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить продукт "{{ object.product_name }}"?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'main:index' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/product_detail.html
{% extends 'main/base.html' %}
{% load media_tag %}
{% block content %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.product_name }}</h4>
        </div>
        <div class="card-body">
            <img class="card-img-top" src="{{ object.product_image|media_tag}}">
            <h1 class="card-title pricing-card-title">{{ object.product_description }}</h1>
            <h1 class="card-title pricing-card-title">{{ object.product_price }} RUB</h1>
            <h1 class="card-title pricing-card-title">{{ object.owner }}</h1>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/product_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Обновить
                            {% else %}
                            Создать
                        {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/product_list.html
{% extends 'main/base.html' %}
{% load media_tag %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'main:create' %}">Добавить продукт</a>
</div>
<div class="row">
    {% for object in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.product_name }}</h4>
            </div>
            <div class="card-body">
                <h2 class="card-title pricing-card-title">{{ object.product_description|slice:5 }} ... </h2>
                <h1 class="card-title pricing-card-title">{{ object.product_price }} RUB</h1>
                <a href="{% url 'main:products' object.pk %}"
                   class="btn btn-sm btn-outline-secondary">View full product</a>
                {% if perms.main.can_edit_product_description and perms.main.can_edit_is_published or user == main.owner %}
                <a href="{% url 'main:edit' object.pk %}" type="button"
                   class="btn btn-sm btn-outline-secondary">Edit product</a>
                {% endif %}
                <a href="{% url 'main:delete' object.pk %}"
                   class="btn btn-sm btn-outline-danger">Delete product</a>
                {% if object.active_version %}
                <a href="{% url 'main:list_versions' object.pk %}"
                   class="btn btn-sm btn-outline-secondary">View product version</a>
                {% endif %}
                <a href="{% url 'main:create_version' object.pk %}"
                   class="btn btn-sm btn-outline-secondary">Create product version</a>
            </div>
            <div>
                {% if object.active_version %}
                <p>Активная версия: {{ object.active_version.version_name }}</p>
                <!-- Другие данные об активной версии, если необходимо -->
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/products.html
{% extends 'main/base.html' %}
{% load media_tag %}
{% block content %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.product_name }}</h4>
        </div>
        <div class="card-body">
            <img class="card-img-top" src="{{ object.product_image|media_tag}}">
            <h1 class="card-title pricing-card-title">{{ object.product_description }}</h1>
            <h1 class="card-title pricing-card-title">{{ object.product_price }} RUB</h1>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/version_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить версию продукта "{{ object.product }}" "{{ object.version_no }}"?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'blogg:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/version_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.product }}</h4>
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title">{{ object.version_no }}</h1>
            <h1 class="card-title pricing-card-title">{{ object.version_name }}</h1>
            <h1 class="card-title pricing-card-title">{{ object.active_version }}</h1>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/version_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Обновить
                            {% else %}
                            Создать
                        {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/version_list.html
{% extends 'main/base.html' %}
{% block content %}
{% for object in object_list %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.product }}</h4>
        </div>
        <div class="card-body">
            <h3 class="card-title pricing-card-title">Номер версии: {{ object.version_no }}</h3>
            <h3 class="card-title pricing-card-title">Название версии: {{ object.version_name }}</h3>
            <a href="{% url 'main:update_version' object.pk %}"
               class="btn btn-sm btn-outline-secondary">Change product version</a>
            <a href="{% url 'main:delete_version' object.pk %}"
               class="btn btn-sm btn-outline-danger">Delete product version</a>
            {% if object.active_version %}
            <h4 class="card-title pricing-card-title" style="color: green">Активная версия</h4>
            {% else %}
            <h4 class="card-title pricing-card-title" style="color: grey">Неактивная версия</h4>
            {% endif %}
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}